application: lono-rain
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: html/index.html
  upload: html/index.html
- url: /Chart.Scatter.js
  static_files: js/Chart.Scatter.js
  upload: js/Chart.Scatter.js
- url: /graph
  static_files: html/graph.html
  upload: html/graph.html
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: ssl
  version: latest